name: Standard CI

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: The target environment
        type: environment
        default: staging
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: "echo 'building ...'"
      - run: "echo 'hooking to ${{ vars.SERVICE_API }}'"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: "echo 'testing ...'"
      - run: "echo 'using API key: ${{ vars.API_KEY }}'"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    environment: ${{ inputs.environment }}
    steps:
      - run: "echo 'deploying to ${{ inputs.environment }} ...'"
