name: Standard CI

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: The target environment
        type: environment
        default: staging
        required: true
jobs:
  build:
    uses: ./.github/workflows/independent_build.yaml

  test:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.build_result == 'success'
    steps:
      - name: Quality check
        run: "exit 1"
      - if: always()
        run: "echo 'testing ...'"
      - run: "echo 'using API key: ${{ secrets.API_KEY }}'"

  deploy:
    if: always()
    runs-on: ubuntu-latest
    needs: [build, test]
    environment: ${{ inputs.environment }}
    steps:
      - run: "echo 'deploying to ${{ inputs.environment }} ...'"
