name: Random workflow for practing concepts

on: workflow_dispatch

permissions:
  contents: read

jobs:
  nike:
    runs-on: ubuntu-latest
    permissions: 
      pages: read
    env:
      a_value: "${{ github.repository }}"
    steps:
      - run: "echo 'doing it!'"
      - run: "echo 'the value set is: ${{ env.a_value }}'"
      - run: "echo running $GITHUB_WORKFLOW"
      - run: "echo 'KEY=VALUE' >> $GITHUB_OUTPUT"
      - run: "echo 'DB_URL=postgress://exmaple.com/db' >> $GITHUB_ENV"
      - run: "echo $GITHUB_OUTPUT"
      - run: "echo $GITHUB_ENV"
